Fix file name
If the file is called 'fuse.py', line 9 'from fuse import...' tries to
import from itself, which obviously leads to an error.

Traceback (most recent call last):
  File "./fuse.py", line 9, in <module>
    from fuse import FUSE, FuseOSError, Operations
  File "/home/julian/dev/python-fuse-sample/fuse.py", line 9, in <module>
    from fuse import FUSE, FuseOSError, Operations
ImportError: cannot import name 'FUSE'